[package]
name = "native_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type =["lib", "cdylib", "staticlib"]

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
tokio = { version = "1.44.0", features = ["full"] }
